---
title: "EDA"
output: github_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(p8105.datasets)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
  )

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
  )

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

Import the weather data
```{r}
data("weather_df")

weather_df <-
  weather_df |> 
  mutate(month = floor_date(date, unit = "month")) # rounds down date to the first date of the month, allow you to create categorical variable to compute by month

# lubridate package - working with dates 
```


Make plots

```{r}
weather_df |> 
  ggplot(aes(x = prcp)) +
  geom_histogram()
```


Check on extreme values 

```{r}
weather_df |> 
  filter(prcp > 1000)
```


Look at data again

```{r}
weather_df |> 
  filter(tmax >=20, tmax <= 30) |> 
  ggplot(aes(x = tmin, y = tmax, color = name, shape = name)) +
  geom_point()
```



## Add groups

```{r}
weather_df |> 
  group_by(name, month) # add grouping structure based on variables you have, can group by multiple categroies
```


Group and count things

```{r}
weather_df |> 
  group_by(name) |> 
  summarize(
    n = n() # how many observations do I have 
  )
```


```{r}
weather_df |> 
  group_by(month) |> 
  summarise(
    n = n()
  )

weather_df |> 
  group_by(name, month) |> 
  summarise(
    n = n()
  )
```


```{r}
weather_df |> 
  group_by(month) |> 
  summarize(
    n = n_distinct(date) # count up distinct instances, not just total number of instances  
  )
```


You can count directly

```{r}
weather_df |> 
  count(name) # group by name and count up number of observations
```


## More interesting summaries

Compute some extra stuff

```{r}
weather_df |> 
  group_by(name, month) |> 
  summarize(
    mean_tmax = mean(tmax, na.rm = TRUE), # mean tmax for each month
    median_tmin = median(tmin, na.rm = TRUE),
    sd_prcp = sd(prcp, na.rm = TRUE)
  )
```


This is still a dataframe!!

```{r}
weather_df |> 
  group_by(name, month) |> 
  summarize(
    mean_tmax = mean(tmax, na.rm = TRUE) 
  ) |> 
  ggplot(aes(x = month, y = mean_tmax, color = name)) +
  geom_point() +
  geom_line()
```


```{r}
weather_df |> 
  group_by(name, month) |> 
  summarize(
    mean_tmax = mean(tmax, na.rm = TRUE) 
  ) |> 
  pivot_wider(
    names_from = name, 
    values_from = mean_tmax
  ) |> 
  knitr::kable(digits = 2)
```


## mutate with groups

```{r}
weather_df |> 
  mutate(
    mean_tmax = mean(tmax, na.rm = TRUE) # the mean_tmax is going to take all the tmax observations and compute mean for each of them, but doing so across all weather stations at all times
  )
```


```{r}
weather_df |> 
  group_by(name) |> 
  mutate(
    mean_tmax = mean(tmax, na.rm = TRUE),
    center_tmax = tmax - mean_tmax
  ) |> 
  ggplot(aes(x = date, y = center_tmax, color = name)) +
  geom_point()
```


Look for cold days

```{r}
weather_df |> 
  group_by(name, month) |> 
  mutate(temp_rank = min_rank(desc(tmin))) |> 
  filter(temp_rank < 2)
```


What about lags?

```{r}
weather_df |> 
  group_by(name) |> # using grpup keeps track of observations by group 
  mutate(lagged_tmax = lag(tmax)) # order matters here!
```


Use the variables you create

```{r}
weather_df |> 
  group_by(name) |> 
  mutate(
    temp_change = tmax - lag(tmax)
  ) |> 
  summarize(
    sd_tmax_change = sd(temp_change, na.rm = TRUE), 
    tmax_change_max = max(temp_change, na.rm = TRUE)
  )
```


```{r}
weather_df |> 
  group_by(name) |> 
  mutate(
    temp_change = tmax - lag(tmax), 
    change_rank = min_rank(desc(temp_change))
  ) |> 
  filter(
    change_rank < 2
  )
```


## Revisit pulse

```{r}
pulse_df <-
  haven::read_sas("data/public_pulse_data.sas7bdat") |> 
  janitor::clean_names() |> 
  pivot_longer(
    bdi_score_bl:bdi_score_12m, 
    names_to = "visit",
    names_prefix = "bdi_score_",
    values_to = "bdi"
  ) |> 
  mutate(visit = fct_inorder(visit))

pulse_df |> 
  ggplot(aes(x = visit, y = bdi)) +
  geom_boxplot()

pulse_df |> 
  group_by(visit) |> 
  summarize(
    mean_bdi = mean(bdi, na.rm = TRUE),
    median_bdi = median(bdi, na.rm = TRUE)
  ) |> 
  knitr::kable(digits = 2)
```

